<?php
require_once __DIR__ . '/AuthRoutes.php';
require_once __DIR__ . '/UserRoutes.php';
require_once __DIR__ . '/RoleRoutes.php';
require_once __DIR__ . '/BookRoutes.php';
require_once __DIR__ . '/FavoriteRoutes.php';
require_once __DIR__ . '/SavedRoutes.php';
require_once __DIR__ . '/TagRoutes.php';
require_once __DIR__. '/DocenteRoutes.php';
require_once __DIR__. '/SeccionRoutes.php';
require_once __DIR__. '/MatriculaRoutes.php';
require_once __DIR__. '/EstudianteRoutes.php';
require_once __DIR__. '/NotasRoutes.php';
require_once __DIR__. '/ClasesRouter.php';
require_once __DIR__. '/AulaRouter.php';
require_once __DIR__. '/JefeRoutes.php';
require_once __DIR__. '/ListaEsperaRoutes.php';
require_once __DIR__. '/ListaCancelacionRoutes.php';
require_once __DIR__. '/DepartamentoRoutes.php';
require_once __DIR__. '/MensajesRoutes.php';
require_once __DIR__. '/ObservacionesRoutes.php';
require_once __DIR__. '/EdificioRoutes.php';
require_once __DIR__. '/EvaluacionRoutes.php';
require_once __DIR__. '/SoliciturAmistadRoutes.php';
require_once __DIR__. '/InfoMatriculaRoutes.php';
require_once __DIR__. '/AmisionesRoutes.php';
require_once __DIR__. '/CarreraRoutes.php';
require_once __DIR__. '/CentroRoutes.php';
require_once __DIR__. '/InfoNotasRoutes.php';
require_once __DIR__. '/InfoAddCanRoutes.php';

function registerAllRoutes($router) {
    registerAuthRoutes($router);
    registerUserRoutes($router);
    registerDocenteRoutes($router);
    registerRoleRoutes($router);
    registerBookRoutes($router);
    registerFavoriteRoutes($router);
    registerSavedRoutes($router);
    registerTagRoutes($router);
    registerSeccionRoutes($router);
    registerMatriculaRoutes($router);
    registerEstudianteRoutes($router);
    registerNotasRoutes($router);
    registerClasesRouter($router);
    registerAulaRoutes($router);
    registerJefeRoutes($router);
    registerEsperaRoutes($router);
    registerCancelacionRoutes($router);
    registerDepartamentoRoutes($router);
    registerMensajesRoutes($router);
    registerObservacionesRoutes($router);
    registerEdificioRoutes($router);
    registerEvaluacionRoutes($router);
    registerSolicitudAmistadRoutes($router);
    registerInfoMatriculaRoutes($router);
    registerAdmisionesRoutes($router);
    registerCarreraRoutes($router);
    registerCentroRoutes($router);
    registerInfoNotasRoutes($router);
    registerInfoAddCanRoutes($router);
}